# Generated by Django 3.2.6 on 2021-11-25 10:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('mid_name', models.CharField(blank=True, max_length=50, verbose_name='Отчетство')),
                ('contract_number', models.CharField(blank=True, max_length=50, verbose_name='Номер заключенного контракта')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='CustomersEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_name', models.CharField(max_length=50, verbose_name='Название оборудования')),
                ('serial_number', models.CharField(max_length=50, verbose_name='Серийный номер')),
            ],
            options={
                'verbose_name': 'Клиентское оборудование',
                'verbose_name_plural': 'Клиентское оборудование',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('mid_name', models.CharField(blank=True, max_length=50, verbose_name='Отчетство')),
                ('post', models.CharField(max_length=50, verbose_name='Занимаемая должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='ListOfEquip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_type', models.CharField(max_length=50, verbose_name='Тип оборудования')),
                ('comments', models.TextField(blank=True, max_length=250, verbose_name='Комментарии')),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Типы оборудования',
            },
        ),
        migrations.CreateModel(
            name='ListOfServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50, verbose_name='Название предоставляемой услуги')),
                ('comments', models.TextField(blank=True, max_length=250, verbose_name='Комментарии')),
            ],
            options={
                'verbose_name': 'Предоставляемая услуга',
                'verbose_name_plural': 'Список предоставляемых услуг',
            },
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_name', models.CharField(max_length=50, verbose_name='Название тарифа')),
                ('fee', models.IntegerField(verbose_name='Стоимость тарифа (руб. в месяц)')),
                ('provided_speed', models.IntegerField(verbose_name='Предоставляемая скорость (Мбит)')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата подключения')),
                ('status', models.CharField(choices=[('Создан', 'Создан'), ('Ожидает оплаты', 'Ожидает оплаты'), ('Ожидает заключения контракта', 'Ожидает заключения контракта'), ('Ожидание подготовки оборудования', 'Ожидание подготовки оборудования'), ('Ожидает выполнения услуг', 'Ожидает выполнения услуг'), ('Отложен', 'Отложен'), ('Завершен', 'Завершен'), ('Отменен', 'Отменен')], default='Создан', max_length=40, verbose_name='Статус заказа')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Client', to='main_app.clients', verbose_name='Клиент')),
                ('customers_equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='main_app.customersequipment', verbose_name='Оборудование')),
                ('employees', models.ManyToManyField(related_name='Orders', to='main_app.Employees', verbose_name='Исполнители')),
                ('rate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Rate', to='main_app.rates', verbose_name='Тариф')),
                ('services', models.ManyToManyField(related_name='Orders', to='main_app.ListOfServices', verbose_name='Предоставляемые услуги')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_name', models.CharField(max_length=50, verbose_name='Название оборудования')),
                ('serial_number', models.CharField(max_length=50, verbose_name='Серийный номер')),
                ('cequip_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Equipment', to='main_app.customersequipment', verbose_name='Клиентское оборудование')),
                ('equip_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Equipment', to='main_app.listofequip', verbose_name='Тип оборудования')),
            ],
            options={
                'verbose_name': 'Клиентское оборудование',
                'verbose_name_plural': 'Клиентское оборудование',
            },
        ),
    ]
